# ==========================
# JPA
# ==========================
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

# ==========================
# Logging
# ==========================
logging.level.com.crowninteractive.assessment=WARN
logging.level.org.flywaydb=WARN

# ==========================
# Actuator
# ==========================
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=when-authorized