# ==========================
# Database
# ==========================
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/assessment_db}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}

# ==========================
# Server
# ==========================
server.port=${SERVER_PORT:8040}

# ==========================
# JPA
# ==========================
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ==========================
# Logging
# ==========================
logging.level.com.crowninteractive.assessment=DEBUG