CREATE TABLE transactions (
                              amount              NUMERIC(19, 2) NOT NULL,
                              created_at          TIMESTAMP(6) WITH TIME ZONE NOT NULL,
                              id                  BIGINT GENERATED BY DEFAULT AS IDENTITY,
                              transaction_date    TIMESTAMP(6) WITH TIME ZONE NOT NULL,
                              updated_at          TIMESTAMP(6) WITH TIME ZONE,
                              account_number      VARCHAR(255) NOT NULL,

                              channel             VARCHAR(255) NOT NULL
                                  CHECK (channel IN (
                                                     'ATM',
                                                     'POS',
                                                     'MOBILE',
                                                     'WEB',
                                                     'TRANSFER'
                                      )),

                              currency            VARCHAR(255) NOT NULL
                                  CHECK (currency IN (
                                                      'NGN',
                                                      'USD',
                                                      'GBP',
                                                      'EUR'
                                      )),

                              slug                VARCHAR(255) NOT NULL UNIQUE,

                              source              VARCHAR(255) NOT NULL
                                  CHECK (source IN (
                                                    'BANK',
                                                    'PAYSTACK',
                                                    'API'
                                      )),

                              status              VARCHAR(255) NOT NULL
                                  CHECK (status IN (
                                                    'PENDING',
                                                    'SUCCESS',
                                                    'FAILED'
                                      )),

                              transaction_reference VARCHAR(255) NOT NULL UNIQUE,

                              transaction_type    VARCHAR(255) NOT NULL
                                  CHECK (transaction_type IN (
                                                              'CREDIT',
                                                              'DEBIT'
                                      )),

                              PRIMARY KEY (id)
);


-- Index on transaction date
CREATE INDEX idx_transactions_transaction_date
    ON transactions (transaction_date);


-- Composite index on account number + transaction date
CREATE INDEX idx_transactions_account_date
    ON transactions (account_number, transaction_date);